### ISSUE TITLE
Global attribute checking changed?

### ISSUE THREAD

**Issue by swr99ejo** [actris-cloudnet/cloudnetpy-qc#8]
This loop doesn't seem to work when checking global attributes for ECMWF model data. Issue started in production for data sent after Sunday 17th September 2023

            or (
                product == Product.MODEL
                and name in ("initialization_time", "institution")
            )
            or (self._instrument_product(product) and name == "serial_number")

**Comment by siiptuo** [comment]
We did some changes to the tests. The current global attribute test works and we just need to re-run the quality control for last couple of days.

However, new test for suspicious floating-point values fails on ECMWF files that contain infinite vertical wind at the first level (e.g. https://cloudnet.fmi.fi/file/621e2e05-c70f-4a57-9f3e-50688a6d4025/quality). Is this expected?

**Comment by swr99ejo** [comment]
Shouldn't happen. However, vertical wind has been calculated from omega (Pa s-1), height and pressure using: w=omega*dz/dp so there has been an issue in calculating dz or dp.

**Comment by siiptuo** [comment]
Maybe dz or dp are calculated using "diff" instead of "gradient" so one value is missing at the end? I managed to compute this with gradient:

![wwind](https://github.com/actris-cloudnet/cloudnetpy-qc/assets/10729330/fb05c1a4-e994-4344-83ff-d46eadf4b00b)
